# Generated by Django 4.2.15 on 2024-08-23 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='completed_at',
        ),
    ]
