# Generated by Django 4.2.15 on 2024-08-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_task_title_taskitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
